### ISSUE TITLE
To run an error FileNotFoundError: [Errno 2] No such file or directory: 'Xorg': 'Xorg'

### ISSUE THREAD

**Issue by zkbutt** [andyljones/coolgpus#14]
(base) feadre@e2680v2:~$ sudo $(which coolgpus) --temp 20 55 80 --speed 5 30 99
[sudo] password for feadre: 
No existing X servers, we're good to go
Starting xserver: Xorg :0 -once -config /tmp/cool-gpu-00000000:03:00.03f8wzkac/xorg.conf
Traceback (most recent call last):
  File "/home/feadre/anaconda3/bin/coolgpus", line 266, in <module>
    run()
  File "/home/feadre/anaconda3/bin/coolgpus", line 259, in run
    with xservers(buses) as displays:
  File "/home/feadre/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/feadre/anaconda3/bin/coolgpus", line 177, in xservers
    servers[bus] = xserver(displays[bus], bus)
  File "/home/feadre/anaconda3/bin/coolgpus", line 137, in xserver
    p = Popen(xorgargs)
  File "/home/feadre/anaconda3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/feadre/anaconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Xorg': 'Xorg'
(base) feadre@e2680v2:~$ sudo $(which coolgpus) 
No existing X servers, we're good to go
Starting xserver: Xorg :0 -once -config /tmp/cool-gpu-00000000:03:00.0g2ui0rm2/xorg.conf
Traceback (most recent call last):
  File "/home/feadre/anaconda3/bin/coolgpus", line 266, in <module>
    run()
  File "/home/feadre/anaconda3/bin/coolgpus", line 259, in run
    with xservers(buses) as displays:
  File "/home/feadre/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/feadre/anaconda3/bin/coolgpus", line 177, in xservers
    servers[bus] = xserver(displays[bus], bus)
  File "/home/feadre/anaconda3/bin/coolgpus", line 137, in xserver
    p = Popen(xorgargs)
  File "/home/feadre/anaconda3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/feadre/anaconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Xorg': 'Xorg'

**Comment by andyljones** [comment]
This is the command it failed on:

```
Xorg :0 -once -config /tmp/cool-gpu-00000000:03:00.0g2ui0rm2/xorg.conf
```

Try running that from your command line, see if you get the same failure. You either don't have `Xorg` installed, or it's not on your PATH.

**Comment by azarezade** [comment]
Is there a way to use coolgpus without X on a gpu server?

**Comment by andyljones** [comment]
nope
